name: telegram message

on:
  pull_request_target:
    types:
      - opened
      - reopened
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.GROUP_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} сделал пулл реквестик:
            ${{ github.event.pull_request.title }}

            Ссылочка: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
