name: telegram message

on:
  pull_request:
    branches: [ "master" ]
    types:
      - opened
      - reopened
      - closed

jobs:
  build:
    uses: ./.github/workflows/gradle.yml
  message:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: build
    steps:
      - if: ${{ github.event.pull_request.merged == 'true' }}
        name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.GROUP_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🎉🎉🎉Произошло слияние: ${{ github.event.pull_request.title }}
          photo: https://i.gifer.com/9NM.gif
      - if: ${{ !contains(needs.*.result, 'failure') && github.event.pull_request.merged == 'false' }}
        name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.GROUP_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} создал пулл реквестик:
            ${{ github.event.pull_request.title }}

            Тестики: ✅

            Ссылочка: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
      - if: ${{ contains(needs.*.result, 'failure') && github.event.pull_request.merged == 'false' }}
        name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.GROUP_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} создал пулл реквестик:
            ${{ github.event.pull_request.title }}

            Тестики: ❌

            Ссылочка: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}

        
