name: telegram message

on:
  pull_request:
    branches: [ "master" ]
    types:
      - opened
      - reopened
      - closed

jobs:
  build:
    uses: ./.github/workflows/gradle.yml
  message:
    steps:
      - if: ${{ success() }}
        name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.GROUP_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} создал пулл реквестик:
            ${{ github.event.pull_request.title }}

            Тестики: ❌

            Ссылочка: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
      - if: ${{ failure() }}
        name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.GROUP_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} создал пулл реквестик:
            ${{ github.event.pull_request.title }}

            Тестики: ✅

            Ссылочка: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}

        
